services:
  app:
    build: .
    container_name: app
    ports:
      - 8000:3000
      - 8001:3001
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
